### ISSUE TITLE
Not waifuing-ffmpeging all frames and only got a partial (9%) output

### ISSUE THREAD

**Issue by rNiubo** [imPRAGMA/W2XKit#2]
Hi!

I was testing your project and I have a problem. Waifu is not upscaling all frames from the folder and when ffmpeg is running to get the final video it only converts to the first "not-existing frame". I did a test and got 3379 output frames but only 3348 frames in the upscaled folder.

There are no initial-ending frames because it were middle-named frames.

Where is the problem? Maybe too many threads rendering and crashing a thread?

Also... What about adding this ffmpeg command to output 4K renders with h264_nvenc too?:
ffmpeg.exe -hwaccel cuvid -i D:\WAIFU2X\frames\upscaled\image-%04d.png -c:v h264_nvenc -preset slow -rc vbr_hq -b:v 35M -maxrate:v 45M outfixed.mp4

Thank you!

**Comment by imPRAGMA** [comment]
So that can occasionaly happen where waifu2x itself fails, thing is waifu2x-caffe's cui program was badly made and doesnt seem to document on how to receive word on any issues that can occur with it. So W2XKit can never really know if it failed on some frames.
Best thing I can help you with is to just delete the original frames that are finished and upscale the non-finished ones again.

**Comment by imPRAGMA** [comment]
As for the ffmpeg command, does ffmpeg really support nvenc? and if so whats the point of using -hwaccel if nvenc is going to be handling it?

**Comment by imPRAGMA** [comment]
Added hwaccel support to Combine.
